services:

  valkey:
    container_name: valkey_currency
    hostname: valkey
    image: valkey/valkey:8.1.0-bookworm
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - cache-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    ports:
      - "6379:6379"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  cache-data:

